import json
import glob
import os

translations = {
    "ar": {"regex": "تعبير عادي (1)", "replace": "استبدال (3)", "remove": "إزالة (5)", "add": "إضافة (7)", "auto_date": "تاريخ تلقائي (8)", "numbering": "ترقيم (10)", "name": "اسم الملف (2)", "case": "حالة الأحرف (4)", "move_copy": "نقل/نسخ (6)", "folder_name": "اسم المجلد (9)", "extension": "امتداد (11)", "selection": "تحديد (12)", "new_location": "موقع جديد (13)"},
    "bn": {"regex": "রেজেক্স (1)", "replace": "প্রতিস্থাপন (3)", "remove": "সরান (5)", "add": "যোগ করুন (7)", "auto_date": "স্বয়ংক্রিয় তারিখ (8)", "numbering": "নম্বর (10)", "name": "ফাইলের নাম (2)", "case": "অক্ষরের আকার (4)", "move_copy": "সরান/কপি করুন (6)", "folder_name": "ফোল্ডারের নাম (9)", "extension": "এক্সটেনশন (11)", "selection": "নির্বাচন (12)", "new_location": "নতুন অবস্থান (13)"},
    "de": {"regex": "Regex (1)", "replace": "Ersetzen (3)", "remove": "Entfernen (5)", "add": "Hinzufügen (7)", "auto_date": "Autom. Datum (8)", "numbering": "Nummerierung (10)", "name": "Dateiname (2)", "case": "Groß-/Kleinschreibung (4)", "move_copy": "Verschieben/Kopieren (6)", "folder_name": "Ordnername (9)", "extension": "Erweiterung (11)", "selection": "Auswahl (12)", "new_location": "Neuer Ort (13)"},
    "en": {"regex": "Regex (1)", "replace": "Replace (3)", "remove": "Remove (5)", "add": "Add (7)", "auto_date": "Auto Date (8)", "numbering": "Numbering (10)", "name": "File Name (2)", "case": "Case (4)", "move_copy": "Move/Copy (6)", "folder_name": "Folder Name (9)", "extension": "Extension (11)", "selection": "Selection (12)", "new_location": "New Location (13)"},
    "es": {"regex": "ExpReg (1)", "replace": "Reemplazar (3)", "remove": "Eliminar (5)", "add": "Añadir (7)", "auto_date": "Fecha Auto (8)", "numbering": "Numeración (10)", "name": "Nombre de Archivo (2)", "case": "Mayús/Minús (4)", "move_copy": "Mover/Copiar (6)", "folder_name": "Nombre de Carpeta (9)", "extension": "Extensión (11)", "selection": "Selección (12)", "new_location": "Nueva Ubicación (13)"},
    "fa": {"regex": "عبارت باقاعده (1)", "replace": "جایگزینی (3)", "remove": "حذف (5)", "add": "افزودن (7)", "auto_date": "تاریخ خودکار (8)", "numbering": "شماره‌گذاری (10)", "name": "نام فایل (2)", "case": "بزرگی و کوچکی حروف (4)", "move_copy": "انتقال/کپی (6)", "folder_name": "نام پوشه (9)", "extension": "پسوند (11)", "selection": "انتخاب (12)", "new_location": "مکان جدید (13)"},
    "fr": {"regex": "Regex (1)", "replace": "Remplacer (3)", "remove": "Supprimer (5)", "add": "Ajouter (7)", "auto_date": "Date Auto (8)", "numbering": "Numérotation (10)", "name": "Nom de Fichier (2)", "case": "Casse (4)", "move_copy": "Déplacer/Copier (6)", "folder_name": "Nom de Dossier (9)", "extension": "Extension (11)", "selection": "Sélection (12)", "new_location": "Nouvel Emplacement (13)"},
    "he": {"regex": "ביטוי רגולרי (1)", "replace": "החלף (3)", "remove": "הסר (5)", "add": "הוסף (7)", "auto_date": "תאריך אוטומטי (8)", "numbering": "מספור (10)", "name": "שם קובץ (2)", "case": "אותיות רישיות (4)", "move_copy": "העבר/העתק (6)", "folder_name": "שם תיקייה (9)", "extension": "סיומת (11)", "selection": "בחירה (12)", "new_location": "מיקום חדש (13)"},
    "hi": {"regex": "रेगेक्स (1)", "replace": "बदलें (3)", "remove": "हटाएं (5)", "add": "जोड़ें (7)", "auto_date": "ऑटो दिनांक (8)", "numbering": "क्रमांकन (10)", "name": "फ़ाइल का नाम (2)", "case": "अक्षर आकार (4)", "move_copy": "स्थानांतरित/कॉपी करें (6)", "folder_name": "फ़ोल्डर का नाम (9)", "extension": "एक्सटेंशन (11)", "selection": "चयन (12)", "new_location": "नया स्थान (13)"},
    "id": {"regex": "Regex (1)", "replace": "Ganti (3)", "remove": "Hapus (5)", "add": "Tambah (7)", "auto_date": "Tanggal Otomatis (8)", "numbering": "Penomoran (10)", "name": "Nama File (2)", "case": "Huruf (4)", "move_copy": "Pindah/Salin (6)", "folder_name": "Nama Folder (9)", "extension": "Ekstensi (11)", "selection": "Pilihan (12)", "new_location": "Lokasi Baru (13)"},
    "it": {"regex": "Regex (1)", "replace": "Sostituisci (3)", "remove": "Rimuovi (5)", "add": "Aggiungi (7)", "auto_date": "Data Auto (8)", "numbering": "Numerazione (10)", "name": "Nome File (2)", "case": "Maiuscole/Minuscole (4)", "move_copy": "Sposta/Copia (6)", "folder_name": "Nome Cartella (9)", "extension": "Estensione (11)", "selection": "Selezione (12)", "new_location": "Nuova Posizione (13)"},
    "ja": {"regex": "正規表現 (1)", "replace": "置換 (3)", "remove": "削除 (5)", "add": "追加 (7)", "auto_date": "自動日付 (8)", "numbering": "連番 (10)", "name": "ファイル名 (2)", "case": "大文字/小文字 (4)", "move_copy": "移動/コピー (6)", "folder_name": "フォルダ名 (9)", "extension": "拡張子 (11)", "selection": "選択 (12)", "new_location": "新しい場所 (13)"},
    "ko": {"regex": "정규식 (1)", "replace": "바꾸기 (3)", "remove": "제거 (5)", "add": "추가 (7)", "auto_date": "자동 날짜 (8)", "numbering": "번호 매기기 (10)", "name": "파일 이름 (2)", "case": "대/소문자 (4)", "move_copy": "이동/복사 (6)", "folder_name": "폴더 이름 (9)", "extension": "확장자 (11)", "selection": "선택 (12)", "new_location": "새 위치 (13)"},
    "ms": {"regex": "Regex (1)", "replace": "Ganti (3)", "remove": "Buang (5)", "add": "Tambah (7)", "auto_date": "Tarikh Auto (8)", "numbering": "Penomboran (10)", "name": "Nama Fail (2)", "case": "Huruf Besar/Kecil (4)", "move_copy": "Pindah/Salin (6)", "folder_name": "Nama Folder (9)", "extension": "Sambungan (11)", "selection": "Pilihan (12)", "new_location": "Lokasi Baru (13)"},
    "nl": {"regex": "Regex (1)", "replace": "Vervangen (3)", "remove": "Verwijderen (5)", "add": "Toevoegen (7)", "auto_date": "Auto Datum (8)", "numbering": "Nummering (10)", "name": "Bestandsnaam (2)", "case": "Hoofdletters/Kleine letters (4)", "move_copy": "Verplaatsen/Kopiëren (6)", "folder_name": "Mapnaam (9)", "extension": "Extensie (11)", "selection": "Selectie (12)", "new_location": "Nieuwe Locatie (13)"},
    "pl": {"regex": "Regex (1)", "replace": "Zastąp (3)", "remove": "Usuń (5)", "add": "Dodaj (7)", "auto_date": "Auto Data (8)", "numbering": "Numerowanie (10)", "name": "Nazwa pliku (2)", "case": "Wielkość liter (4)", "move_copy": "Przenieś/Kopiuj (6)", "folder_name": "Nazwa folderu (9)", "extension": "Rozszerzenie (11)", "selection": "Wybór (12)", "new_location": "Nowa lokalizacja (13)"},
    "pt": {"regex": "Regex (1)", "replace": "Substituir (3)", "remove": "Remover (5)", "add": "Adicionar (7)", "auto_date": "Data Automática (8)", "numbering": "Numeração (10)", "name": "Nome do Arquivo (2)", "case": "Maiúsculas/Minúsculas (4)", "move_copy": "Mover/Copiar (6)", "folder_name": "Nome da Pasta (9)", "extension": "Extensão (11)", "selection": "Seleção (12)", "new_location": "Novo Local (13)"},
    "pt_BR": {"regex": "Regex (1)", "replace": "Substituir (3)", "remove": "Remover (5)", "add": "Adicionar (7)", "auto_date": "Data Automática (8)", "numbering": "Numeração (10)", "name": "Nome do Arquivo (2)", "case": "Maiúsculas/Minúsculas (4)", "move_copy": "Mover/Copiar (6)", "folder_name": "Nome da Pasta (9)", "extension": "Extensão (11)", "selection": "Seleção (12)", "new_location": "Novo Local (13)"},
    "ru": {"regex": "Регулярное (1)", "replace": "Заменить (3)", "remove": "Удалить (5)", "add": "Добавить (7)", "auto_date": "Авто Дата (8)", "numbering": "Нумерация (10)", "name": "Имя файла (2)", "case": "Регистр (4)", "move_copy": "Переместить/Копировать (6)", "folder_name": "Имя папки (9)", "extension": "Расширение (11)", "selection": "Выбор (12)", "new_location": "Новое место (13)"},
    "sw": {"regex": "Regex (1)", "replace": "Badilisha (3)", "remove": "Ondoa (5)", "add": "Ongeza (7)", "auto_date": "Tarehe Kiotomatiki (8)", "numbering": "Kuweka Namba (10)", "name": "Jina la Faili (2)", "case": "Herufi (4)", "move_copy": "Hamisha/Nakili (6)", "folder_name": "Jina la Folda (9)", "extension": "Kiendelezi (11)", "selection": "Uchaguzi (12)", "new_location": "Mahali Papya (13)"},
    "ta": {"regex": "ரெஜெக்ஸ் (1)", "replace": "மாற்று (3)", "remove": "அகற்று (5)", "add": "சேர் (7)", "auto_date": "தானியங்கி தேதி (8)", "numbering": "எண்ணிடுதல் (10)", "name": "கோப்பு பெயர் (2)", "case": "எழுத்து வகை (4)", "move_copy": "நகர்த்து/நகலெடு (6)", "folder_name": "கோப்புறை பெயர் (9)", "extension": "நீட்டிப்பு (11)", "selection": "தேர்வு (12)", "new_location": "புதிய இடம் (13)"},
    "th": {"regex": "นิพจน์ปกติ (1)", "replace": "แทนที่ (3)", "remove": "ลบ (5)", "add": "เพิ่ม (7)", "auto_date": "วันที่อัตโนมัติ (8)", "numbering": "การกำหนดหมายเลข (10)", "name": "ชื่อไฟล์ (2)", "case": "ตัวพิมพ์เล็ก/ใหญ่ (4)", "move_copy": "ย้าย/คัดลอก (6)", "folder_name": "ชื่อโฟลเดอร์ (9)", "extension": "นามสกุล (11)", "selection": "การเลือก (12)", "new_location": "ตำแหน่งใหม่ (13)"},
    "tl": {"regex": "Regex (1)", "replace": "Palitan (3)", "remove": "Alisin (5)", "add": "Idagdag (7)", "auto_date": "Auto Petsa (8)", "numbering": "Pagkakasunod-sunod (10)", "name": "Pangalan ng File (2)", "case": "Laki ng Titik (4)", "move_copy": "I-move/Kopyahin (6)", "folder_name": "Pangalan ng Folder (9)", "extension": "Extension (11)", "selection": "Pagpili (12)", "new_location": "Bagong Lokasyon (13)"},
    "tr": {"regex": "Regex (1)", "replace": "Değiştir (3)", "remove": "Kaldır (5)", "add": "Ekle (7)", "auto_date": "Oto Tarih (8)", "numbering": "Numaralandırma (10)", "name": "Dosya Adı (2)", "case": "Büyük/Küçük Harf (4)", "move_copy": "Taşı/Kopyala (6)", "folder_name": "Klasör Adı (9)", "extension": "Uzantı (11)", "selection": "Seçim (12)", "new_location": "Yeni Konum (13)"},
    "uk": {"regex": "Регулярний (1)", "replace": "Замінити (3)", "remove": "Видалити (5)", "add": "Додати (7)", "auto_date": "Авто Дата (8)", "numbering": "Нумерація (10)", "name": "Ім'я файлу (2)", "case": "Регістр (4)", "move_copy": "Перемістити/Копіювати (6)", "folder_name": "Ім'я папки (9)", "extension": "Розширення (11)", "selection": "Вибір (12)", "new_location": "Нове місце (13)"},
    "ur": {"regex": "ریجیکس (1)", "replace": "تبدیل کریں (3)", "remove": "ہٹائیں (5)", "add": "شامل کریں (7)", "auto_date": "خودکار تاریخ (8)", "numbering": "نمبرنگ (10)", "name": "فائل کا نام (2)", "case": "حروف کی حالت (4)", "move_copy": "منتقل/کاپی کریں (6)", "folder_name": "فولڈر کا نام (9)", "extension": "ایکسٹینشن (11)", "selection": "انتخاب (12)", "new_location": "نیا مقام (13)"},
    "vi": {"regex": "Regex (1)", "replace": "Thay thế (3)", "remove": "Xóa (5)", "add": "Thêm (7)", "auto_date": "Ngày tự động (8)", "numbering": "Đánh số (10)", "name": "Tên tệp (2)", "case": "Chữ hoa/thường (4)", "move_copy": "Di chuyển/Sao chép (6)", "folder_name": "Tên thư mục (9)", "extension": "Phần mở rộng (11)", "selection": "Lựa chọn (12)", "new_location": "Vị trí mới (13)"},
    "zh_TW": {"regex": "正規表示式 (1)", "replace": "取代 (3)", "remove": "移除 (5)", "add": "新增 (7)", "auto_date": "自動日期 (8)", "numbering": "編號 (10)", "name": "檔案名稱 (2)", "case": "大小寫 (4)", "move_copy": "移動/複製 (6)", "folder_name": "附加資料夾名 (9)", "extension": "副檔名 (11)", "selection": "選擇過濾 (12)", "new_location": "新位置 (13)"}
}

for f in glob.glob('locales/*.json'):
    lang_code = os.path.basename(f).split('.')[0]
    if lang_code in translations:
        try:
            with open(f, 'r', encoding='utf-8') as file:
                d = json.load(file)
            
            rules = d.get('main_window', {}).get('rules', {})
            changed = False
            
            for k, title_val in translations[lang_code].items():
                if k in rules:
                    rules[k]['title'] = title_val
                    changed = True
                    
            if changed:
                with open(f, 'w', encoding='utf-8') as file:
                    json.dump(d, file, ensure_ascii=False, indent=4)
                print(f"Updated {lang_code} titles successfully.")
        except Exception as e:
            print(f"Error processing {f}: {e}")
